name: NodeJS with Webpack workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Get the repository
      uses: actions/checkout@v3

    - name: Install and setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21.5.0

    - name: Install project dependencies
      run: npm i

    - name: Build the project
      run: npm run build

    - name: Upload the build as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "dist"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v4
 
